ingress:
  ## Set to true to enable ingress record generation
  enabled: true

  host: longhorn.k3s.myvision.me
  
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: longhorn-system-basic-auth@kubernetescrd

  tls:
  - hosts:
    - longhorn.k3s.myvision.me                 
    secretName: longhorn.k3s.myvision.me-prod-tls