ingress:
  ## Set to true to enable ingress record generation
  enabled: true

  host: longhorn.k3s.myvision.me
  
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # Whitelist public IP to restrict access
    # TODO replace this with something more sensible or disable ingress alltogether
    ingress.kubernetes.io/whitelist-source-range: "x.x.x.x/32"

  tls:
  - hosts:
    - longhorn.k3s.myvision.me                 
    secretName: longhorn.k3s.myvision.me-prod-tls